spring.application.name=security

#Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/igiris?TimeZone=Asia/Kolkata
spring.datasource.username=madara
spring.datasource.password=madara
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

#JWT utilities
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=${JWT_EXPIRATION}